# This file is part of the Ocrend Framewok 2 package.
#
# (c) Ocrend Software <info@ocrend.com>
#
# For the full copyright and license information, please view the LICENS
# file that was distributed with this source code.

# Conexión con la base de datos principal
database:
  host: localhost
  user: root
  pass: 
  name: ocrend
  port: 1521
  protocol: TCP
  motor: mysql
  
# Configuración de servidor SMTP
phpmailer:
  host: s510.tmd.cloud
  user: developer@ocrend.com
  pass: Developer-+*
  port: 465

# Configuración de sesiones
sessions:
  unique: 0CR3ND2017
  life_time: 3600 

# Variables del framework
framework:
  debug: false
  version: 2.0.4

# Api configuración
youtube:
  name: prinick-com
  api: AIzaSyDOwGCfDRHoVUWT26KEm6JJ9J4NWj1Zg-M

# Configuración del sitio
site:
  name: PRINICK - Blogger, Desarrollo Web, Tutoriales y Juegos
  author: Brayan Narváez
  author_email: prinick@ocrend.com
  timezone: America/Caracas
  url: http://localhost/prinick.com/
  router:
    path: localhost/prinick.com/
    protocol: http
